config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :sorianas do
    collection do
      post :import
      get 'remove_all'

    end
  end
    root to: 'sorianas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :soriana
end

app/models/soriana.rb
class Soriana < ApplicationRecord
def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |soriana|
      csv << soriana.attributes.values_at(*column_names)
    end
  end
end


def self.import(file)
  spreadsheet = Roo::Spreadsheet.open(file.path)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
    soriana = find_by(id: row["id"]) || new
    soriana.attributes = row.to_hash
    soriana.save!
  end
end

def self.open_spreadsheet(file)
case File.extname(file.original_filename)
when ".csv" then Roo::CSV.new(file.path, nil, :ignore)
when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
else raise "Unknown file type: #{file.original_filename}"
end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   def respond_modal_with(*args, &blk)
     options = args.extract_options!
     options[:responder] = ModalResponder
     respond_with *args, options, &blk
   end
end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base

  private

    def client_params
      params.require(:client).permit(:name, :phone, :soriana_id)
    end
end

app/controllers/sorianas_controller.rb
class SorianasController < ApplicationController
  before_action :set_soriana, only: [:show, :edit, :update, :destroy]

respond_to :html, :json

  # GET /sorianas
  # GET /sorianas.json
  def index
    @sorianas = Soriana.all
    respond_to do |format|
      format.html
      format.csv { send_data @sorianas.to_csv }
      format.xls
    end
  end
  def import
  Soriana.import(params[:file])

  redirect_to root_url, notice: 'Venta importada'
  end

  # GET /sorianas/1
  # GET /sorianas/1.json
  def show
    @soriana = Soriana.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Prawn::Document.new
          pdf.text "Venta \##{@soriana.id}", size: 30, style: :bold
          pdf.text "Producto: #{@soriana.product}", size: 30, style: :bold
          pdf.text "Precio: \$#{@soriana.price}.00", size: 30, style: :bold
          pdf.text "Cantidad: #{@soriana.quantity}", size: 30, style: :bold
          pdf.text "Total: \$#{@soriana.price * @soriana.quantity}.00", size: 30, style: :bold
          send_data pdf.render, filename:"soriana_#{@soriana.id}.pdf", type: "application/pdf",disposition: "inline"
        end
      end
  end

  # GET /sorianas/new
  def new
    @soriana = Soriana.new
    respond_modal_with @soriana
  end

  # GET /sorianas/1/edit
  def edit
    respond_modal_with @soriana
  end

  # POST /sorianas
  # POST /sorianas.json
  def create
    @soriana = Soriana.new(soriana_params)
    respond_modal_with @soriana, location: sorianas_path

    respond_to do |format|
      if @soriana.save
        format.html { redirect_to @soriana, notice: 'Soriana was successfully created.' }
        format.json { render :show, status: :created, location: @soriana }
      else
        format.html { render :new }
        format.json { render json: @soriana.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sorianas/1
  # PATCH/PUT /sorianas/1.json
  def update
    respond_to do |format|
      if @soriana.update(soriana_params)
        format.html { redirect_to @soriana, notice: 'Soriana was successfully updated.' }
        format.json { render :show, status: :ok, location: @soriana }
      else
        format.html { render :edit }
        format.json { render json: @soriana.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sorianas/1
  # DELETE /sorianas/1.json
  def destroy
    @soriana.destroy
    respond_to do |format|
      format.html { redirect_to sorianas_url, notice: 'Soriana was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_soriana
      @soriana = Soriana.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def soriana_params
      params.require(:soriana).permit(:product, :price, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/sorianas_helper.rb
module SorianasHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :phone %>
    <%=  f.select :soriana_id, options_for_select(Soriana.all.map{|s|[s.product, s.id]}) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Compras</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Compra</th>
      <th>Cantidad</th>
      <th>Total a pagar</th>
      <th>Fecha</th>
      <th colspan="3"> Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.phone %></td>
        <td><%= client.soriana.product %></td>
        <td><%= client.soriana.quantity %></td>
        <%total= client.soriana.quantity * client.soriana.price %>
        <td><%= "\$#{total}.00" %></td>
        <td><%= client.created_at.strftime("%d-%m-%Y")%></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path, class: 'btn btn-success'%>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Venta:</strong>
  <%= @client.soriana.product %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%=stylesheet_link_tag 'bootstrap.min.css'%>
    <%=javascript_include_tag 'bootstrap.js'%>
    <%=javascript_include_tag 'modal.js'%>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container justify-content-between">
        <%= link_to 'Soriana', root_path, class: 'navbar-brand' %>

        <%= link_to 'Agregar Venta', new_soriana_path, class: 'btn btn-outline-success my-2 my-sm-0', data: { modal: true } %>
      </div>
    </nav>
    </header>
  <div class="container">
      <%= yield %>
    </div>
    <div id="modal-holder"></div>
  </body>
</html>

app/views/layouts/modal.html.erb
<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= yield %>
    </div>
  </div>
</div>

app/views/sorianas/_form.html.erb
<%= simple_form_for(soriana, remote: request.xhr?, html: { data: { modal: true } }) do |form| %>
  <div class="modal-body">
    <div class="field">
      <%= form.label :'Product: ' %>
      <%= form.text_field :product %>
    </div>

    <div class="field">
      <%= form.label :'Price: ' %>
      <%= form.number_field :price %>
    </div>

    <div class="field">
      <%= form.label :'Quantity: ' %>
      <%= form.number_field :quantity %>
    </div>
  </div>

  <div class="modal-footer">
    <%= form.button :submit, class: 'btn-success' %>
    <%= link_to 'Back', sorianas_path %>
  </div>
<%end%>

app/views/sorianas/edit.html.erb
<div class="modal-header">
  <h5 class="modal-title">Editar Venta</h5>
</div>
<%= render 'form', soriana: @soriana %>

app/views/sorianas/index.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag 'soriana.png' %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Producto</th>
      <th>Precio</th>
      <th>Cantidad</th>
      <th>Total</th>
      <th colspan="3"> Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @sorianas.each do |soriana| %>
      <tr>
        <td><%= soriana.product %></td>
        <td><%= "\$#{soriana.price}.00" %></td>
        <td><%= soriana.quantity %></td>
        <td><%="\$#{soriana.price * soriana.quantity}.00"%></td>
        <td><%= link_to soriana_path(soriana.id, format: 'pdf') do%>
          <li class="fa fa-search"></li>
        <%end%></td>
        <td><%= link_to edit_soriana_path(soriana), data: { modal: true } do%>
          <li class="fa fa-pencil"> </li>
        <%end%></td>
        <td><%= link_to soriana, method: :delete, data: { confirm: 'Are you sure?' } do%>
          <li class="fa fa-trash"></li>
        <%end%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<center>
<h5>Total: <%= "\$#{Soriana.pluck('sum(price * quantity)').join}.00"%></h2>
</center

<br>

<p style="font-size:120%;">
  Descargar:
  <%= link_to "CSV", sorianas_path(format: "csv") %> |
  <%= link_to "Excel", sorianas_path(format: "xls") %>
</p>
<br>
<h2>Importar ventas</h2>
<%= form_tag import_sorianas_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Importar" %>
<% end %>

app/views/sorianas/index.xls.erb
<table border="1">
    <tr>
      <th>Product</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>

    <% @sorianas.each do |soriana| %>
      <tr>
        <td><%= soriana.product %></td>
        <td><%= soriana.price %></td>
        <td><%= soriana.quantity %></td>
        <td><%= link_to 'Show', soriana %></td>
        <td><%= link_to 'Edit', edit_soriana_path(soriana) %></td>
        <td><%= link_to 'Destroy', soriana, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

app/views/sorianas/new.html.erb
<div class="modal-header">
  <h5 class="modal-title">Nueva Venta</h5>
</div>
<%= render 'form', soriana: @soriana %>

app/views/sorianas/new.js.erb
$('<%= j render "form", title: "Publicar Venta" %>').modal();

app/views/sorianas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @soriana.product %>
</p>

<p>
  <strong>Price:</strong>
  <%= @soriana.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @soriana.quantity %>
</p>

<%= link_to 'Edit', edit_soriana_path(@soriana) %> |
<%= link_to 'Back', sorianas_path %>